### ISSUE TITLE
Realizar Pruebas Unitarias del API

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/core_crud#3]
Se debe realizar pruebas unitarias para probar los metodos GET PUT GET ID y DELETE, como guia para el equipo de desarrollo de Campus.

Lider Técnica @mafeave

**Comment by fabianbarreto02** [comment]
Se realizan las pruebas  para el controlador tipo_periodo, esta es una tabla paramétrica, el desarrollo de las pruebas se implementan con la libreria Godog, para esto es necesario crear 3 directorios dentro de la carpeta test:

- conf: contiene las variables de entorno del api, 
- feature: contiene las step que se van a realizar las prueba para los dos escenarios el primero es para revisar los codigos de conexion del controlador y el segundo escenario realiza las pruebas de los 4 métodos
- la ultima carpeta contiene los JSON de los request del api y los response que se esperan en las pruebas. 

Revisar todos los commits donde se explica paso a paso las pruebas en la rama [prueba_test](https://github.com/udistrital/core_crud/tree/prueba_test).

**Comment by fabianbarreto02** [comment]
Se espera revisión tecnica por parte de @mafeave

**Comment by mafeave** [comment]
Pendiente:
- revisión con Arquitectos y Grupo de Seguridad en reunión del lunes 26 de agosto a las 2:00 pm.
- agregar documentación de las pruebas realizadas.

**Comment by fabianbarreto02** [comment]
Se anexa [documento](https://docs.google.com/document/d/1Uuk4IQHjhwm-3rQWwsmZQ5uts6X3SCEJ8OpJEsvUHXU/edit) guia sobre las pruebas unitarias para controladores que manejen tabla parametricas.

**Comment by mafeave** [comment]
Se hace socialización con @jjvargass en reunión del día 26 de Agosto, queda como observación, revisar la ejecución de las pruebas con pipeline de drone en preproducción (test)
